In [243]:
import os
def generate_key(length):
    """Generate a random key of the specified length."""
    return os.urandom(length)

def xor_encrypt_decrypt(plaintext, key):
    """Encrypt or decrypt using XOR operation."""
    return bytes([p ^ k for p, k in zip(plaintext, key)])

def main():
    # Input plaintext
    plaintext = input("Enter the plaintext: ").encode('utf-8')  # Convert to bytes

    # Generate a random key of the same length as the plaintext
    key = generate_key(len(plaintext))
    print(f"Generated Key (hex): {key.hex()}")

    # Encrypt the plaintext
    ciphertext = xor_encrypt_decrypt(plaintext, key)
    print(f"Ciphertext (hex): {ciphertext.hex()}")

    # Decrypt the ciphertext
    decrypted_text = xor_encrypt_decrypt(ciphertext, key)
    print(f"Decrypted Text: {decrypted_text.decode('utf-8')}")

if __name__ == "__main__":
    main()
    # print()

Enter the plaintext:  shree123


Generated Key (hex): 274b8946231fac40
Ciphertext (hex): 5423fb23462e9e73
Decrypted Text: shree123


In [244]:
import os

def generate_key_binary(length):
    """Generate a random binary key of the specified length."""
    return ''.join(format(byte, '08b') for byte in os.urandom((length + 7) // 8))[:length]

def xor_binary(plaintext_binary, key_binary):
    """Perform XOR operation on two binary strings."""
    return ''.join(str(int(p) ^ int(k)) for p, k in zip(plaintext_binary, key_binary))

def text_to_binary(text):
    """Convert text to a binary string."""
    return ''.join(format(ord(char), '08b') for char in text)

def binary_to_text(binary):
    """Convert a binary string to text."""
    return ''.join(chr(int(binary[i:i+8], 2)) for i in range(0, len(binary), 8))

def main():
    # Input plaintext
    plaintext = input("Enter the plaintext: ")

    # Convert plaintext to binary
    plaintext_binary = text_to_binary(plaintext)
    print(f"Plaintext (binary): {plaintext_binary}")

    # Generate a random binary key of the same length as the plaintext binary
    key_binary = generate_key_binary(len(plaintext_binary))
    print(f"Generated Key (binary): {key_binary}")

    # Encrypt the plaintext binary using XOR
    ciphertext_binary = xor_binary(plaintext_binary, key_binary)
    print(f"Ciphertext (binary): {ciphertext_binary}")

    # Decrypt the ciphertext binary using XOR
    decrypted_binary = xor_binary(ciphertext_binary, key_binary)
    print(f"Decrypted Binary: {decrypted_binary}")

    # Convert decrypted binary back to text
    decrypted_text = binary_to_text(decrypted_binary)
    print(f"Decrypted Text: {decrypted_text}")

if __name__ == "__main__":
    main()

Enter the plaintext:  fqavadabv


Plaintext (binary): 011001100111000101100001011101100110000101100100011000010110001001110110
Generated Key (binary): 011111111010000101000010010000001010010110000101101011001111011011101011
Ciphertext (binary): 000110011101000000100011001101101100010011100001110011011001010010011101
Decrypted Binary: 011001100111000101100001011101100110000101100100011000010110001001110110
Decrypted Text: fqavadabv


In [205]:
import torch
from torch import nn
from torch.utils.data import DataLoader
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import random
import numpy as np
from PIL import Image
import pandas as pd
import os 
import matplotlib.pyplot as plt
import math
import random
import torch.nn.functional as F

words=open('names.txt').read().splitlines()
chars=sorted(list(set(''.join(words))))
s_to_i={s:i+1 for i,s in enumerate(chars) }
s_to_i['.']=0
i_to_s={i:s for s,i in s_to_i.items()}
for n in range(10):
    s_to_i[str(n)]=n+27
    

s_to_i

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0,
 '0': 27,
 '1': 28,
 '2': 29,
 '3': 30,
 '4': 31,
 '5': 32,
 '6': 33,
 '7': 34,
 '8': 35,
 '9': 36}

In [287]:
plain_text='ssk9'
l=[]
for p in plain_text:
    l.append(s_to_i[p])

l

[19, 19, 11, 36]

In [4]:
import hashlib

def sha256_hash(input_string):
    # Convert the input string to bytes (using UTF-8 encoding)
    input_bytes = input_string.encode('utf-8')
    # Create a SHA-256 hash object
    hash_object = hashlib.sha256(input_bytes)
    # Get the hexadecimal digest of the hash
    hash_hex = hash_object.hexdigest()
    return hash_hex

# Example input (less than 256 bits; "hello" is 5 bytes = 40 bits)
input_str = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
hash_result = sha256_hash(input_str)

print("Input:", input_str)
print("SHA-256 Hash:", hash_result)
len(hash_result)

Input: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
SHA-256 Hash: d7914fe546b684688bb95f4f888a92dfc680603a75f23eb823658031fff766d9


64

In [326]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import TensorDataset, DataLoader

# Set random seed for reproducibility
np.random.seed(0)
torch.manual_seed(0)

# Create a small dataset: 1000 random binary vectors (16 bits each)
data_np = np.random.randint(0, 2, size=(1000, 64)).astype(np.float32)
data_tensor = torch.tensor(data_np)

len(data_tensor)


1000

In [327]:
# Define the Autoencoder model
class Autoencoder(nn.Module):
    def __init__(self, input_dim=64, encoding_dim=100):
        super(Autoencoder, self).__init__()
        # Encoder: Compress input from 16 -> 8 dimensions
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, encoding_dim),
            nn.BatchNorm1d(encoding_dim),
            nn.ReLU(),
            nn.Linear(encoding_dim, encoding_dim),
            nn.BatchNorm1d(encoding_dim),
            nn.ReLU(),
        )
        # Decoder: Reconstruct from 8 -> 16 dimensions
        self.decoder = nn.Sequential(
            nn.Linear(encoding_dim, input_dim),
            nn.BatchNorm1d(input_dim),
            nn.ReLU(),
            nn.Linear(input_dim, input_dim),
            nn.BatchNorm1d(input_dim),
            nn.Sigmoid()  
        )
    
    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

    def encode(self,x):
        return self.encoder(x)

    def decode(self,x):
        return self.decoder(x)

model = Autoencoder(input_dim=64, encoding_dim=64)
criterion = nn.BCELoss()  # Binary Cross Entropy Loss for binary data
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Prepare DataLoader
dataset = TensorDataset(data_tensor, data_tensor)  # input and target are the same
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [328]:
# Train the autoencoder
num_epochs = 500
for epoch in range(num_epochs):
    epoch_loss = 0.0
    for batch_inputs, batch_targets in dataloader:
        optimizer.zero_grad()
        encoded, outputs = model(batch_inputs)
        loss = criterion(outputs, batch_targets)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item() * batch_inputs.size(0)
    epoch_loss /= len(dataloader.dataset)
    if (epoch + 1) % 100 == 0 or epoch == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}")



Epoch [1/500], Loss: 0.7450
Epoch [100/500], Loss: 0.0716
Epoch [200/500], Loss: 0.0263
Epoch [300/500], Loss: 0.0176
Epoch [400/500], Loss: 0.0123
Epoch [500/500], Loss: 0.0109


In [329]:
seed=10023
np.random.seed(seed)
torch.manual_seed(seed)
data_np = np.random.randint(0, 2, size=(1000, 64)).astype(np.float32)
data_tensor = torch.tensor(data_np)
sample = data_tensor[0:1]  #
# sample=torch.randint(1,64)
# sample=torch.tensor([[1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0.]])
model.eval()
with torch.no_grad():
    encoded_sample, reconstructed_sample = model(sample)


binary_reconstructed = (reconstructed_sample > 0.5).float()
print(torch.equal(sample,binary_reconstructed))
print("\nOriginal sample:")
print(sample)
print("\nEncoded (latent) representation (this is the 'encrypted' form):")
print(encoded_sample)
print("Reconstructed sample (continuous values):")
print(reconstructed_sample)
print("\nRounded (binary) reconstructed sample:")
print(binary_reconstructed)

True

Original sample:
tensor([[0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
         1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
         1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
         1., 0., 1., 1., 0., 1., 1., 1., 0., 0.]])

Encoded (latent) representation (this is the 'encrypted' form):
tensor([[1.2465, 2.1475, 0.8052, 1.2717, 0.9031, 1.2692, 0.9743, 0.5665, 1.6724,
         1.1594, 1.1305, 1.2119, 1.4683, 0.4801, 1.0859, 0.4298, 0.0000, 1.3949,
         0.7743, 1.5731, 0.0741, 0.6663, 1.8297, 1.2946, 0.7864, 0.4782, 1.0969,
         0.5623, 0.7337, 0.9710, 0.5024, 1.8548, 1.5597, 0.6515, 0.4654, 0.6143,
         1.2348, 1.9755, 1.1505, 1.1808, 1.0390, 0.5361, 1.0927, 0.3523, 2.0917,
         1.0682, 1.0327, 1.1262, 0.9073, 2.0615, 2.2165, 1.3452, 0.8511, 1.2595,
         0.9778, 0.4548, 1.7272, 0.6038, 1.0162, 1.0049, 1.0052, 0.8650, 1.5515,
         0.8391]])
Reconstructed sample (continuous

In [356]:
import torch

def binary_tensor_to_word(binary_tensor):
    """
    Converts a PyTorch tensor of shape (1, 64) containing binary digits (0 or 1)
    into an 8-character word by interpreting every 8 bits as one ASCII character.
    """
    # Ensure the tensor is 1-dimensional (flatten it)
    bits = binary_tensor.view(-1).tolist()  # This will be a list of 64 values
    
    # Convert every group of 8 bits to a character
    chars = []
    for i in range(0, 64, 8):
        # Get 8 bits for one character
        chunk = bits[i:i+8]
        # Convert the 8 bits into a string, e.g. [0,1,0,0,0,0,0,1] -> "01000001"
        bit_string = ''.join(str(int(b)) for b in chunk)
        # Convert the bit string to an integer (base 2)
        ascii_val = int(bit_string, 2)
        # Convert the integer to a character using the chr() function
        chars.append(chr(ascii_val))
    
    # Join the list of characters to form a word
    return ''.join(chars)


def word_to_binary_tensor(word):
    """
    Converts an 8-character word into a PyTorch tensor of shape (1, 64)
    containing binary digits (0 or 1) by representing each character in 8 bits.
    """
    if len(word) != 8:
        raise ValueError("The input word must be exactly 8 characters long.")
    
    bits_list = []
    for char in word:
        # Convert character to its ASCII value and then to an 8-bit binary string
        bin_str = format(ord(char), '08b')
        # Extend the list with each bit as an integer (0 or 1)
        bits_list.extend([int(bit) for bit in bin_str])
    
    # Convert the list to a PyTorch tensor and reshape to (1, 64)
    binary_tensor = torch.tensor(bits_list, dtype=torch.float32).view(1, 64)
    return binary_tensor

# Example: Create a tensor of shape (1, 64) representing the word "Hello!!!"
# Let's compute the binary representation for each character in "Hello!!!"
word = "sk28skk2"
binary_list = []
for char in word:
    # Format each character's ASCII value into an 8-bit binary string
    binary_str = format(ord(char), '08b')
    # Extend our list with each bit as an integer (0 or 1)
    binary_list.extend([int(bit) for bit in binary_str])

binary_tensor = torch.tensor([binary_list], dtype=torch.float32)

model.eval()
with torch.no_grad():
    encoded_sample, reconstructed_sample = model(binary_tensor)


binary_reconstructed = (reconstructed_sample > 0.5).float()

binary_tensor = binary_reconstructed
decoded_word = binary_tensor_to_word(binary_tensor)
encoded_word = binary_tensor_to_word((F.sigmoid(encoded_sample)>0.5).float())
print("Decoded word:", decoded_word)
print("encoded word:", encoded_word)


Decoded word: sk28skk2
encoded word: ûÿÿÿÿÿÿÿ


In [342]:
print(torch.equal(binary_tensor,binary_reconstructed))
print("\nOriginal sample:")
print(sample)
print("\nEncoded (latent) representation (this is the 'encrypted' form):")
print(encoded_sample)
print("Reconstructed sample (continuous values):")
print(reconstructed_sample)
print("\nRounded (binary) reconstructed sample:")
print(binary_reconstructed)

True

Original sample:
tensor([[0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
         1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
         1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
         1., 0., 1., 1., 0., 1., 1., 1., 0., 0.]])

Encoded (latent) representation (this is the 'encrypted' form):
tensor([[0.6475, 1.2431, 1.2816, 1.2411, 1.9890, 0.1787, 1.2939, 0.0000, 1.4897,
         0.9581, 1.2690, 1.2688, 1.2769, 1.4227, 0.7585, 1.9031, 1.1169, 0.6847,
         1.3349, 0.9564, 0.6493, 0.6915, 0.6775, 1.5787, 0.9446, 1.5311, 0.5918,
         1.3049, 0.8853, 1.9289, 0.9315, 1.7201, 1.1374, 0.5466, 0.6487, 0.9272,
         1.5619, 1.1883, 1.1913, 1.9067, 1.4519, 1.2111, 1.3409, 1.5193, 1.5256,
         0.1543, 2.3070, 1.6005, 1.7102, 1.5064, 2.1893, 1.0729, 1.6569, 2.0508,
         0.9580, 2.1150, 0.8074, 1.1153, 1.0356, 0.8391, 1.3190, 0.6820, 0.6381,
         0.8715]])
Reconstructed sample (continuous

In [347]:
import torch.nn.functional as F 
word = "11111111"
binary_list = []
for char in word:
    # Format each character's ASCII value into an 8-bit binary string
    binary_str = format(ord(char), '08b')
    # Extend our list with each bit as an integer (0 or 1)
    binary_list.extend([int(bit) for bit in binary_str])

binary_tensor = torch.tensor([binary_list], dtype=torch.float32)

model.eval()
with torch.no_grad():
    encoded_sample, reconstructed_sample = model(binary_tensor)

# F.sigmoid(encoded_sample)
cipher_in = (F.sigmoid(encoded_sample) > 0.5).float()

print(cipher_in.shape)
# Input plaintext
ciphertext_in = (binary_tensor_to_word(cipher_in)).encode('utf-8') # Convert to bytes
print(binary_tensor_to_word(cipher_in))
print(ciphertext_in)
# print(len(binary_tensor_to_word(cipher_in)))
# Generate a random key of the same length as the plaintext
key = generate_key(len(ciphertext_in))
print(f"Generated Key  {key}")
print(f"ciphertext_in: {ciphertext_in}")
# Encrypt the plaintext
ciphertext_mid = xor_encrypt_decrypt(ciphertext_in, key)
print(f"Ciphertext_mid: {ciphertext_mid}")

# Decrypt the ciphertext
ciphertext_out = xor_encrypt_decrypt(ciphertext_mid, key)
print(f"ciphertext_out: {ciphertext_out}")

binnary_tensor=word_to_binary_tensor(ciphertext_out.decode('UTF-8'))
print(ciphertext_out.decode('UTF-8'))
print(torch.equal(binary_tensor,cipher_in))
print(binary_tensor,cipher_in)
# model.eval()
# with torch.no_grad():
#     binary_reconstructed=model.decode(binary_tensor)

# decoded_word = binary_tensor_to_word(binary_reconstructed)
# print("Decoded word:", decoded_word)

torch.Size([1, 64])
þÿÿÿÿÿÿÿ
b'\xc3\xbe\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf'
Generated Key  b'\xdc\xf8J\x03\xba0\xecY{\x97:g\x19\xf1\xc7\x7f'
ciphertext_in: b'\xc3\xbe\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf'
Ciphertext_mid: b'\x1fF\x89\xbcy\x8f/\xe6\xb8(\xf9\xd8\xdaN\x04\xc0'
ciphertext_out: b'\xc3\xbe\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf\xc3\xbf'
þÿÿÿÿÿÿÿ
False
tensor([[0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
         1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
         0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
         0., 1., 0., 0., 1., 1., 0., 0., 0., 1.]]) tensor([[1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [324]:
from Crypto.Cipher import DES
from Crypto.Util.Padding import pad, unpad

def des_encrypt(plaintext: bytes, key: bytes) -> bytes:
    """
    Encrypts plaintext using DES in ECB mode.
    
    :param plaintext: Data to encrypt (as bytes).
    :param key: 8-byte key (as bytes).
    :return: The encrypted ciphertext (as bytes).
    """
    if len(key) != 8:
        raise ValueError("Key must be exactly 8 bytes long for DES.")
    cipher = DES.new(key, DES.MODE_ECB)
    # DES works on 8-byte blocks; pad the plaintext if necessary.
    padded_text = pad(plaintext, DES.block_size)
    ciphertext = cipher.encrypt(padded_text)
    return ciphertext

def des_decrypt(ciphertext: bytes, key: bytes) -> bytes:
    """
    Decrypts ciphertext using DES in ECB mode.
    
    :param ciphertext: Data to decrypt (as bytes).
    :param key: 8-byte key (as bytes).
    :return: The recovered plaintext (as bytes).
    """
    if len(key) != 8:
        raise ValueError("Key must be exactly 8 bytes long for DES.")
    cipher = DES.new(key, DES.MODE_ECB)
    padded_plaintext = cipher.decrypt(ciphertext)
    # Remove the padding to get the original plaintext.
    plaintext = unpad(padded_plaintext, DES.block_size)
    return plaintext


In [325]:
import torch.nn.functional as F 
word = "Shree123"
binary_list = []
for char in word:
    # Format each character's ASCII value into an 8-bit binary string
    binary_str = format(ord(char), '08b')
    # Extend our list with each bit as an integer (0 or 1)
    binary_list.extend([int(bit) for bit in binary_str])

binary_tensor = torch.tensor([binary_list], dtype=torch.float32)

model.eval()
with torch.no_grad():
    encoded_sample, reconstructed_sample = model(binary_tensor)

# F.sigmoid(encoded_sample)
cipher_in = (F.sigmoid(encoded_sample) > 0.5).float()

print(cipher_in.shape)
# Input plaintext
ciphertext_in = (binary_tensor_to_word(cipher_in)).encode('UTF-8')
print(ciphertext_in)

key = generate_key(len(ciphertext_in))
print(f"Generated Key  {key}")
print(f"ciphertext_in: {ciphertext_in}")

ciphertext_mid =des_encrypt(ciphertext_in, key)
print(f"Ciphertext_mid: {ciphertext_mid}")

# Decrypt the ciphertext
ciphertext_out = des_decrypt(ciphertext_mid, key)
print(f"ciphertext_out: {ciphertext_out}")

binnary_tensor=word_to_binary_tensor(ciphertext_out.decode('UTF-8'))
print(binary_tensor.shape)


torch.Size([1, 300])
b'\xc3\xb7{\xc3\xbf\xc3\xac\xc3\xaf\xc2\xbf\x7f\xc2\xbf'
Generated Key  b'\tK\xdb\xf7\xfd\xb4S\x95\xcdu\xc8\xb0o0'
ciphertext_in: b'\xc3\xb7{\xc3\xbf\xc3\xac\xc3\xaf\xc2\xbf\x7f\xc2\xbf'


ValueError: Key must be exactly 8 bytes long for DES.